--
-- PostgreSQL database dump
--

\restrict uyCZKpuWfI2ipZdhPfOIDtQhkfJkarvXT5uJvmRmFNYLP2BWdZajYMWS8ZYHBYh

-- Dumped from database version 17.6 (Debian 17.6-2.pgdg13+1)
-- Dumped by pg_dump version 17.6 (Debian 17.6-2.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Name: admin; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.admin (
    admin_id integer NOT NULL,
    admin_epost text NOT NULL,
    admin_passord_hash text NOT NULL,
    navn text,
    failed_attempts integer DEFAULT 0 NOT NULL,
    lockout_until timestamp with time zone
);


ALTER TABLE public.admin OWNER TO postgres;

--
-- Name: admin_admin_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.admin ALTER COLUMN admin_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.admin_admin_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bedrift; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bedrift (
    bedrift_id integer NOT NULL,
    bedrift_navn character varying(45) NOT NULL,
    bedrift_epost character varying(45) NOT NULL,
    beskrivelse character varying(100)
);


ALTER TABLE public.bedrift OWNER TO postgres;

--
-- Name: bedrift_bedrift_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.bedrift ALTER COLUMN bedrift_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bedrift_bedrift_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bedrift_kompetanse; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bedrift_kompetanse (
    id integer NOT NULL,
    bedrift_id integer NOT NULL,
    fagomrade_id integer NOT NULL,
    kompetanse_id integer NOT NULL,
    underkompetanse_id integer,
    beskrivelse character varying(200),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    modified_at timestamp with time zone,
    modified_by_bedrift_id integer
);


ALTER TABLE public.bedrift_kompetanse OWNER TO postgres;

--
-- Name: bedrift_kompetanse_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.bedrift_kompetanse ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bedrift_kompetanse_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fagomrade; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fagomrade (
    fagomrade_id integer NOT NULL,
    fagomrade_navn character varying(45),
    "BedriftId" integer
);


ALTER TABLE public.fagomrade OWNER TO postgres;

--
-- Name: fagomrade_fagomrade_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.fagomrade ALTER COLUMN fagomrade_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fagomrade_fagomrade_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fagomrade_has_kompetanse; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.fagomrade_has_kompetanse (
    fagomrade_id integer NOT NULL,
    kompetanse_id integer NOT NULL
);


ALTER TABLE public.fagomrade_has_kompetanse OWNER TO postgres;

--
-- Name: kompetanse; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.kompetanse (
    kompetanse_id integer NOT NULL,
    kompetanse_kategori character varying(45)
);


ALTER TABLE public.kompetanse OWNER TO postgres;

--
-- Name: kompetanse_kompetanse_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.kompetanse ALTER COLUMN kompetanse_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kompetanse_kompetanse_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: login_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.login_token (
    id integer NOT NULL,
    bedrift_id integer NOT NULL,
    code_hash text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    attempts integer NOT NULL,
    consumed_at timestamp with time zone
);


ALTER TABLE public.login_token OWNER TO postgres;

--
-- Name: login_token_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.login_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.login_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: under_kompetanse; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.under_kompetanse (
    underkompetanse_id integer NOT NULL,
    underkompetanse_navn character varying(45),
    kompetanse_id integer
);


ALTER TABLE public.under_kompetanse OWNER TO postgres;

--
-- Name: under_kompetanse_underkompetanse_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.under_kompetanse ALTER COLUMN underkompetanse_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.under_kompetanse_underkompetanse_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: admin PK_admin; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.admin
    ADD CONSTRAINT "PK_admin" PRIMARY KEY (admin_id);


--
-- Name: bedrift_kompetanse bedrift_kompetanse_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bedrift_kompetanse
    ADD CONSTRAINT bedrift_kompetanse_pkey PRIMARY KEY (id);


--
-- Name: bedrift bedrift_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bedrift
    ADD CONSTRAINT bedrift_pkey PRIMARY KEY (bedrift_id);


--
-- Name: fagomrade_has_kompetanse fagomrade_has_kompetanse_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fagomrade_has_kompetanse
    ADD CONSTRAINT fagomrade_has_kompetanse_pkey PRIMARY KEY (fagomrade_id, kompetanse_id);


--
-- Name: fagomrade fagomrade_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fagomrade
    ADD CONSTRAINT fagomrade_pkey PRIMARY KEY (fagomrade_id);


--
-- Name: kompetanse kompetanse_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kompetanse
    ADD CONSTRAINT kompetanse_pkey PRIMARY KEY (kompetanse_id);


--
-- Name: login_token login_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.login_token
    ADD CONSTRAINT login_token_pkey PRIMARY KEY (id);


--
-- Name: under_kompetanse under_kompetanse_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.under_kompetanse
    ADD CONSTRAINT under_kompetanse_pkey PRIMARY KEY (underkompetanse_id);


--
-- Name: IX_fagomrade_BedriftId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_fagomrade_BedriftId" ON public.fagomrade USING btree ("BedriftId");


--
-- Name: IX_fagomrade_has_kompetanse_kompetanse_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_fagomrade_has_kompetanse_kompetanse_id" ON public.fagomrade_has_kompetanse USING btree (kompetanse_id);


--
-- Name: IX_under_kompetanse_kompetanse_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_under_kompetanse_kompetanse_id" ON public.under_kompetanse USING btree (kompetanse_id);


--
-- Name: ix_bedrift_kompetanse_bedrift_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_bedrift_kompetanse_bedrift_id ON public.bedrift_kompetanse USING btree (bedrift_id);


--
-- Name: ix_bedrift_kompetanse_fagomrade_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_bedrift_kompetanse_fagomrade_id ON public.bedrift_kompetanse USING btree (fagomrade_id);


--
-- Name: ix_bedrift_kompetanse_kompetanse_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_bedrift_kompetanse_kompetanse_id ON public.bedrift_kompetanse USING btree (kompetanse_id);


--
-- Name: ix_bedrift_kompetanse_underkompetanse_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_bedrift_kompetanse_underkompetanse_id ON public.bedrift_kompetanse USING btree (underkompetanse_id);


--
-- Name: ix_login_token_bedrift_expires; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX ix_login_token_bedrift_expires ON public.login_token USING btree (bedrift_id, expires_at);


--
-- Name: ux_bedrift_kompetanse_unique_choice_active; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX ux_bedrift_kompetanse_unique_choice_active ON public.bedrift_kompetanse USING btree (bedrift_id, fagomrade_id, kompetanse_id, underkompetanse_id) WHERE (is_active = true);


--
-- Name: fagomrade FK_fagomrade_bedrift_BedriftId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fagomrade
    ADD CONSTRAINT "FK_fagomrade_bedrift_BedriftId" FOREIGN KEY ("BedriftId") REFERENCES public.bedrift(bedrift_id);


--
-- Name: fagomrade_has_kompetanse fagomrade_has_kompetanse_fagomrade_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fagomrade_has_kompetanse
    ADD CONSTRAINT fagomrade_has_kompetanse_fagomrade_id_fkey FOREIGN KEY (fagomrade_id) REFERENCES public.fagomrade(fagomrade_id);


--
-- Name: fagomrade_has_kompetanse fagomrade_has_kompetanse_kompetanse_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.fagomrade_has_kompetanse
    ADD CONSTRAINT fagomrade_has_kompetanse_kompetanse_id_fkey FOREIGN KEY (kompetanse_id) REFERENCES public.kompetanse(kompetanse_id);


--
-- Name: bedrift_kompetanse fk_bedrift_kompetanse_bedrift; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bedrift_kompetanse
    ADD CONSTRAINT fk_bedrift_kompetanse_bedrift FOREIGN KEY (bedrift_id) REFERENCES public.bedrift(bedrift_id) ON DELETE RESTRICT;


--
-- Name: bedrift_kompetanse fk_bedrift_kompetanse_fagomrade; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bedrift_kompetanse
    ADD CONSTRAINT fk_bedrift_kompetanse_fagomrade FOREIGN KEY (fagomrade_id) REFERENCES public.fagomrade(fagomrade_id) ON DELETE RESTRICT;


--
-- Name: bedrift_kompetanse fk_bedrift_kompetanse_kompetanse; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bedrift_kompetanse
    ADD CONSTRAINT fk_bedrift_kompetanse_kompetanse FOREIGN KEY (kompetanse_id) REFERENCES public.kompetanse(kompetanse_id) ON DELETE RESTRICT;


--
-- Name: bedrift_kompetanse fk_bedrift_kompetanse_underkompetanse; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bedrift_kompetanse
    ADD CONSTRAINT fk_bedrift_kompetanse_underkompetanse FOREIGN KEY (underkompetanse_id) REFERENCES public.under_kompetanse(underkompetanse_id) ON DELETE RESTRICT;


--
-- Name: login_token fk_login_token_bedrift; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.login_token
    ADD CONSTRAINT fk_login_token_bedrift FOREIGN KEY (bedrift_id) REFERENCES public.bedrift(bedrift_id) ON DELETE CASCADE;


--
-- Name: under_kompetanse under_kompetanse_kompetanse_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.under_kompetanse
    ADD CONSTRAINT under_kompetanse_kompetanse_id_fkey FOREIGN KEY (kompetanse_id) REFERENCES public.kompetanse(kompetanse_id);


--
-- PostgreSQL database dump complete
--

\unrestrict uyCZKpuWfI2ipZdhPfOIDtQhkfJkarvXT5uJvmRmFNYLP2BWdZajYMWS8ZYHBYh

